//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class PaginaConsejos extends JPanel {
    private JLabel labelLogo;
    private JButton buttonPaginaDondeTirarlo;
    private JButton buttonPaginaConsejos;
    private JButton buttonPaginaRegistrarse;
    private JButton buttonPaginaIniciarSesion;
    private JLabel labelConsejo;
    private JTextArea fieldConsejo;

    public PaginaConsejos() {
        //construct components
        labelLogo = new JLabel ("EcoSoul");
        buttonPaginaDondeTirarlo = new JButton ("Donde tirarlo?");
        buttonPaginaConsejos = new JButton ("Consejos");
        buttonPaginaRegistrarse = new JButton ("Registrarse");
        buttonPaginaIniciarSesion = new JButton ("Iniciar Sesion");
        labelConsejo = new JLabel ("Consejo:");
        fieldConsejo = new JTextArea (5, 5);

        //adjust size and set layout
        setPreferredSize (new Dimension (702, 456));
        setLayout (null);

        //add components
        add (labelLogo);
        add (buttonPaginaDondeTirarlo);
        add (buttonPaginaConsejos);
        add (buttonPaginaRegistrarse);
        add (buttonPaginaIniciarSesion);
        add (labelConsejo);
        add (fieldConsejo);

        //set component bounds (only needed by Absolute Positioning)
        labelLogo.setBounds (20, 20, 100, 25);
        buttonPaginaDondeTirarlo.setBounds (85, 20, 125, 25);
        buttonPaginaConsejos.setBounds (215, 20, 125, 25);
        buttonPaginaRegistrarse.setBounds (415, 20, 115, 25);
        buttonPaginaIniciarSesion.setBounds (535, 20, 115, 25);
        labelConsejo.setBounds (45, 95, 100, 25);
        fieldConsejo.setBounds (120, 95, 100, 75);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("PaginaConsejos");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new PaginaConsejos());
        frame.pack();
        frame.setVisible (true);
    }
}
