//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class PaginaDondeTirarlo extends JPanel {
    private JLabel labelLogo;
    private JButton buttonPaginaDondeTirarlo;
    private JButton buttonPaginaConsejos;
    private JButton buttonPaginaRegistrarse;
    private JButton buttonPaginaIniciarSesion;
    private JRadioButton checkPapel;
    private JLabel labelPregunta;
    private JRadioButton checkBotellas;
    private JLabel labelPapel;
    private JLabel labelBotellas;
    private JRadioButton checkCarton;
    private JLabel labelCarton;
    private JRadioButton checkVidrio;
    private JLabel labelVidrio;
    private JLabel labelResultado;
    private JRadioButton buttonComidaSi;
    private JRadioButton buttonComidaNo;
    private JLabel labelComida;
    private JTextArea fieldResultado;
    private JRadioButton checkMetal;
    private JRadioButton checkOtro;
    private JLabel labelMetal;
    private JLabel labelOtro;

    public PaginaDondeTirarlo() {
        //construct components
        labelLogo = new JLabel ("EcoSoul");
        buttonPaginaDondeTirarlo = new JButton ("Donde tirarlo?");
        buttonPaginaConsejos = new JButton ("Consejos");
        buttonPaginaRegistrarse = new JButton ("Registrarse");
        buttonPaginaIniciarSesion = new JButton ("Iniciar Sesion");
        checkPapel = new JRadioButton ("Papel");
        labelPregunta = new JLabel ("Que material vas a reciclar?");
        checkBotellas = new JRadioButton ("Botellas");
        labelPapel = new JLabel ("Descripcion papel.");
        labelBotellas = new JLabel ("Descripcion botellas.");
        checkCarton = new JRadioButton ("Carton");
        labelCarton = new JLabel ("Descripcion carton.");
        checkVidrio = new JRadioButton ("Vidrio");
        labelVidrio = new JLabel ("Descripcion vidrio.");
        labelResultado = new JLabel ("Resultado:");
        buttonComidaSi = new JRadioButton ("Si.");
        buttonComidaNo = new JRadioButton ("No.");
        labelComida = new JLabel ("Contaminado de comida?");
        fieldResultado = new JTextArea (5, 5);
        checkMetal = new JRadioButton ("Metal");
        checkOtro = new JRadioButton ("Otro");
        labelMetal = new JLabel ("Descripcion metal.");
        labelOtro = new JLabel ("Descripcion otro.");

        //adjust size and set layout
        setPreferredSize (new Dimension (702, 456));
        setLayout (null);

        //add components
        add (labelLogo);
        add (buttonPaginaDondeTirarlo);
        add (buttonPaginaConsejos);
        add (buttonPaginaRegistrarse);
        add (buttonPaginaIniciarSesion);
        add (checkPapel);
        add (labelPregunta);
        add (checkBotellas);
        add (labelPapel);
        add (labelBotellas);
        add (checkCarton);
        add (labelCarton);
        add (checkVidrio);
        add (labelVidrio);
        add (labelResultado);
        add (buttonComidaSi);
        add (buttonComidaNo);
        add (labelComida);
        add (fieldResultado);
        add (checkMetal);
        add (checkOtro);
        add (labelMetal);
        add (labelOtro);

        //set component bounds (only needed by Absolute Positioning)
        labelLogo.setBounds (20, 20, 100, 25);
        buttonPaginaDondeTirarlo.setBounds (85, 20, 125, 25);
        buttonPaginaConsejos.setBounds (215, 20, 125, 25);
        buttonPaginaRegistrarse.setBounds (415, 20, 115, 25);
        buttonPaginaIniciarSesion.setBounds (535, 20, 115, 25);
        checkPapel.setBounds (30, 95, 100, 25);
        labelPregunta.setBounds (25, 65, 190, 25);
        checkBotellas.setBounds (30, 165, 100, 25);
        labelPapel.setBounds (40, 120, 125, 25);
        labelBotellas.setBounds (40, 190, 125, 25);
        checkCarton.setBounds (200, 95, 100, 25);
        labelCarton.setBounds (210, 120, 120, 25);
        checkVidrio.setBounds (200, 165, 100, 25);
        labelVidrio.setBounds (210, 190, 120, 25);
        labelResultado.setBounds (130, 285, 100, 25);
        buttonComidaSi.setBounds (550, 110, 100, 25);
        buttonComidaNo.setBounds (550, 140, 100, 25);
        labelComida.setBounds (535, 65, 160, 25);
        fieldResultado.setBounds (265, 280, 345, 100);
        checkMetal.setBounds (370, 95, 100, 25);
        checkOtro.setBounds (370, 165, 100, 25);
        labelMetal.setBounds (380, 120, 120, 25);
        labelOtro.setBounds (380, 190, 100, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("PaginaDondeTirarlo");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new PaginaDondeTirarlo());
        frame.pack();
        frame.setVisible (true);
    }
}
