//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Registrarse extends JPanel {
    private JTextField fieldUsuario;
    private JLabel labelUser;
    private JLabel labelContrasena;
    private JButton buttonIniciar;
    private JButton buttonCancelar;
    private JPasswordField fieldContrasena;
    private JLabel labelaEmail;
    private JTextField jcomp8;

    public Registrarse() {
        //construct components
        fieldUsuario = new JTextField (5);
        labelUser = new JLabel ("Usuario:");
        labelContrasena = new JLabel ("Contrasena:");
        buttonIniciar = new JButton ("Registrarse");
        buttonCancelar = new JButton ("Cancelar");
        fieldContrasena = new JPasswordField (5);
        labelaEmail = new JLabel ("Email:");
        jcomp8 = new JTextField (5);

        //adjust size and set layout
        setPreferredSize (new Dimension (786, 456));
        setLayout (null);

        //add components
        add (fieldUsuario);
        add (labelUser);
        add (labelContrasena);
        add (buttonIniciar);
        add (buttonCancelar);
        add (fieldContrasena);
        add (labelaEmail);
        add (jcomp8);

        //set component bounds (only needed by Absolute Positioning)
        fieldUsuario.setBounds (110, 40, 135, 25);
        labelUser.setBounds (30, 40, 100, 25);
        labelContrasena.setBounds (30, 100, 100, 25);
        buttonIniciar.setBounds (10, 145, 125, 25);
        buttonCancelar.setBounds (150, 145, 125, 25);
        fieldContrasena.setBounds (110, 100, 135, 25);
        labelaEmail.setBounds (30, 70, 100, 25);
        jcomp8.setBounds (110, 70, 135, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("Registrarse");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Registrarse());
        frame.pack();
        frame.setVisible (true);
    }
}
